version: "3.9"

services:
  db:
    image: postgis/postgis
    container_name: eac_postgres
    restart: always
    environment:
      POSTGRES_DB: euamocerrado
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/backup
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./backend
    container_name: eac_backend
    command: python manage.py runserver 0.0.0.0:8585
    volumes:
      - ./backend:/app
    ports:
      - "8585:8585"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DATABASE_URL=postgres://postgres:123456@db:5432/euamocerrado

  #GRAPH-QL que serve os dados para o frontend
  hasura:
    image: hasura/graphql-engine:v2.36.12
    container_name: eac_hassura
    ports:
    - "8383:80"
    depends_on:
    - "db"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:123456@db:5432/euamocerrado
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"

      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # Accepts from all domain
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_DISABLE_CORS: 'true'
      HASURA_GRAPHQL_SERVER_HOST: "*"
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_SERVER_PORT: 80

volumes:
  pgdata:
